// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lanlbjogoaelaslrrtsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhbmxiam9nb2FlbGFzbHJydHN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczOTY1NzcsImV4cCI6MjA3Mjk3MjU3N30.8Xn_Pnfv_kmnrPjQY8bth6Wt4VAC7XV-EW6bre5Khfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});